### ISSUE TITLE
Seg.fault when passed nils

### ISSUE THREAD

**Issue by harbu** [dbalatero/levenshtein-ffi#2]
Hi, great extension!

I noticed that if you pass distance a nil argument it will cause a segmentation fault. Maybe there could be a nil check in the Ruby code?

ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]

**Comment by dbalatero** [comment]
Sure, want to add it?

What is the correct behaviour for a nil argument? Should this be the case:

``` ruby
distance(nil, "string") # => 6
distance("string", nil) # => 6
distance(nil, nil) # => 0? raise an exception?
```

**Comment by mutewinter** [comment]
Just got bit by this also. Would be awesome if it checked for nils and at least through an exception.

**Comment by dbalatero** [comment]
This is fixed in `master`, closing.
